name: on-push
on:
  push:
    branches:
      - '**'

jobs:
  lint-test-build:
    name: lint test build
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: 'npm'

      - name: cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: run affected:lint
        run: npx nx affected:lint --base=${{ github.ref }}

      - name: run affected:test
        run: npx nx affected:test --base=${{ github.ref }}

      - name: run affected:e2e
        run: npx nx affected:e2e --base=${{ github.ref }}

      - name: run build-storybook
        run: npx nx build-storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: dist/storybook/react-chat

      - name: nx build-react-chat
        run: npx nx run react-chat:build:production

      - name: nx build-api
        run: npx nx run api:build:production
      # TODO: Deploy main stack
