name: on-push
on:
  push:
    branches:
      - '**'

jobs:
  lint-test-build:
    name: lint test build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: 'npm'
      - name: cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: run affected
        run: nx affected:lint --base=${{ github.ref }}
      - name: run affected:test
        run: nx affected:test --base=${{ github.ref }}
      - name: run affected:e2e
        run: nx affected:e2e --base=${{ github.ref }}
      # TODO: Add storybook build
      - name: nx affected:build
        run: nx affected:build --base=${{ github.ref }}
      # TODO: Deploy
